name: Java CI

on: [push]

env:
  PACT_BROKER_BASE_URL: ${{secrets.ENV_PACT_BROKER_TOKEN}}
  PACT_BROKER_TOKEN: ${{secrets.ENV_PACT_BROKER_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: show env variables
        run: env

      - name: Build and publish results
        run: make build